# Generated by Django 2.1.1 on 2018-10-16 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180912_0217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
