# Generated by Django 2.1.1 on 2018-10-17 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_original', models.CharField(max_length=100)),
                ('url_resultado', models.CharField(max_length=100)),
                ('fch_muestra', models.DateTimeField()),
                ('fch_analisis', models.DateTimeField()),
                ('observaciones', models.CharField(max_length=1000)),
                ('experimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimento.Experimento')),
            ],
        ),
    ]
