# Generated by Django 2.1.1 on 2018-09-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_original', models.CharField(max_length=100)),
                ('url_resultado', models.CharField(max_length=100)),
                ('fch_muestra', models.DateTimeField()),
                ('fch_analisis', models.DateTimeField()),
                ('observaciones', models.CharField(max_length=1000)),
                ('paciente', models.CharField(max_length=50)),
            ],
        ),
    ]
