# Generated by Django 2.1.1 on 2018-09-26 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experimento', '0003_experimento_sexo'),
        ('analisis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='paciente',
        ),
        migrations.AddField(
            model_name='resultado',
            name='experimento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='experimento.Experimento'),
            preserve_default=False,
        ),
    ]
