# Generated by Django 2.1.1 on 2018-10-17 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionTratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('fch_inicio', models.DateTimeField()),
                ('fch_fin', models.DateTimeField()),
                ('experimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimento.Experimento')),
            ],
        ),
        migrations.AddField(
            model_name='observaciontratamiento',
            name='fk_tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tratamiento.Tratamiento'),
        ),
    ]
