# Generated by Django 2.1.1 on 2018-09-25 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experimento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimento',
            old_name='codigo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='experimento',
            name='name',
        ),
    ]
