# Generated by Django 2.1.1 on 2018-09-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimento', '0002_auto_20180924_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimento',
            name='sexo',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
    ]
