# Generated by Django 2.1.1 on 2018-09-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimento', '0003_experimento_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='gp_sanguineo',
            field=models.CharField(max_length=2),
        ),
    ]
